services:
  postgres:
    image: postgres:15
    container_name: diet-support-postgres
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: diet_support_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    secrets:
      - postgres_user
      - postgres_password
    networks:
      - diet-support-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: diet-support-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL_FILE: /run/secrets/pgadmin_email
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pgadmin_password
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    secrets:
      - pgadmin_email
      - pgadmin_password
    depends_on:
      - postgres
    networks:
      - diet-support-network

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: diet-support-api
    environment:
      NODE_ENV: development
      DATABASE_URL_FILE: /run/secrets/database_url
    ports:
      - "3333:3333"
    volumes:
      - ./apps/api:/app/apps/api
      - ./libs:/app/libs
      - /app/node_modules
    secrets:
      - database_url
    depends_on:
      - postgres
    networks:
      - diet-support-network

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    container_name: diet-support-frontend
    ports:
      - "4200:4200"
    volumes:
      - ./apps/frontend:/app/apps/frontend
      - ./libs:/app/libs
      - /app/node_modules
    depends_on:
      - api
    networks:
      - diet-support-network

secrets:
  postgres_user:
    file: ./secrets/postgres_user.txt
  postgres_password:
    file: ./secrets/postgres_password.txt
  pgadmin_email:
    file: ./secrets/pgadmin_email.txt
  pgadmin_password:
    file: ./secrets/pgadmin_password.txt
  database_url:
    file: ./secrets/database_url.txt

volumes:
  postgres_data:
  pgadmin_data:

networks:
  diet-support-network:
    driver: bridge
