services:
  app:
    build: ./api
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    networks:
      - backend

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    networks:
      - backend

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: diet-support
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    secrets:
      - postgres_user
      - postgres_password
    networks:
      - backend

  redis:
    image: redis:7-alpine
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4:8
    environment:
      PGADMIN_DEFAULT_EMAIL_FILE: /run/secrets/pgadmin_email
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pgadmin_password
    ports:
      - "5050:80"
    secrets:
      - pgadmin_email
      - pgadmin_password
    networks:
      - management
      - backend


volumes:
  postgres-data:

secrets:
  pgadmin_email:
    file: ./secrets/pgadmin_email.txt
  pgadmin_password:
    file: ./secrets/pgadmin_password.txt
  postgres_user:
    file: ./secrets/postgres_user.txt
  postgres_password:
    file: ./secrets/postgres_password.txt

networks:
  backend:
  management:
